name: User App Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 'Run Tests'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Clone project
      uses: actions/checkout@v4

    - name: SetUp Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Store Playwright's Version
      run: |
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/1/ms-playwright/
        key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true
      env:
        URL: ${{ secrets.URL}}
        CI_RUN: true

    - name: Attach Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report
        path: reports/html-report/
        retention-days: 30

    - name: Attach JSON report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: json-report
        path: reports/json-report/test-results.json
        retention-days: 30

    - name: Attach Monocart report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: monocart-report
        path: reports/monocart-report/index.html
        retention-days: 30
