name: User App Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 'Run Tests'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Clone project
      uses: actions/checkout@v4

    - name: SetUp Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        URL: ${{ secrets.URL}}
        CI_RUN: true

    - name: Attach Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report
        path: reports/html-report/
        retention-days: 30

    - name: Attach JUnit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: junit-report
        path: reports/junit-report/test-results.xml
        retention-days: 30

    - name: Create TestRun Report
      uses: dorny/test-reporter@v1.9.1
      if: success() || failure()
      with:
        name: JUnit Tests
        path: reports/junit-report/test-results.xml
        reporter: jest-junit